Source/TechTalkDemo.ASPNETCore2.2/TechTalkDemo.ASPNETCore2.2/Areas/ProgramDetails/Models/ProgramDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TechTalkDemo.ASPNETCore2._2.Areas.ProgramDetails.Models
{
    public class ProgramDetail
    {
         
            public Int32 ProgramId { get; set; }
            public Int32 StartYear { get; set; }
            public string ProgramCode { get; set; }
            public string ProgramName { get; set; }
            public string ProgramDesc { get; set; }
            public int Duration { get; set; }
            public string ProgramType { get; set; }
            public int IsDelete { get; set; }
        
    }
}
  

Source/TechTalkDemo.ASPNETCore2.2/TechTalkDemo.ASPNETCore2.2/Areas/ProgramDetails/Controllers/ProgramDetailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TechTalkDemo.ASPNETCore2._2.Areas.ProgramDetails.Data;
using TechTalkDemo.ASPNETCore2._2.Areas.ProgramDetails.Models;
using TechTalkDemo.Common;

namespace TechTalkDemo.ASPNETCore2._2.Areas.ProgramDetails.Controllers
{
    [Area(TechTalkDemo.Common.AreaName.ProgramDetails)]
    public class ProgramDetailController : Controller
    {


        private readonly IProgramDetailRepository _programDetailRepository;

        public ProgramDetailController(IProgramDetailRepository programDetailRepository)
        {
            _programDetailRepository = programDetailRepository;
        }
         


        [Route(URLRouting.Program.ProgramDetails)]
        public IActionResult ViewProgramDetails()
        {
            return View(_programDetailRepository.GetProgramDetails());
        }
        [Route(URLRouting.Program.AddProgramDetails)]
        public IActionResult AddProgramDetails()
        {
            return View();
        }
        [Route(URLRouting.Program.EditProgramDetails)]
        public IActionResult EditProgramDetails(int Id)
        {
            DataTable dataTable = _programDetailRepository.GetProgramInfoById(Id);

            ProgramDetail student = new ProgramDetail();
            student.ProgramId = Convert.ToInt32(dataTable.Rows[0][DBFields.ProgramDetails.ProgramId]);
            student.StartYear = Convert.ToInt32(dataTable.Rows[0][DBFields.ProgramDetails.StartYear].ToString());
            student.ProgramCode = dataTable.Rows[0][DBFields.ProgramDetails.ProgramCode].ToString();
            student.ProgramName = dataTable.Rows[0][DBFields.ProgramDetails.ProgramName].ToString();
            student.ProgramDesc = dataTable.Rows[0][DBFields.ProgramDetails.ProgramDesc].ToString();
            student.Duration = Convert.ToInt32(dataTable.Rows[0][DBFields.ProgramDetails.Duration].ToString());
            student.ProgramType = dataTable.Rows[0][DBFields.ProgramDetails.ProgramType].ToString();
            
            return View(ControllersList.ProgramDetailsController.ViewAddProgramDetails, student);
             
        }

        [Route(URLRouting.Program.SaveProgramDetails)]
        public IActionResult SaveProgram(ProgramDetail programDetail)
        {
            _programDetailRepository.SaveProgramInfo(programDetail);

            return RedirectToAction(ControllersList.ProgramDetailsController.ActionViewProgramDetails);
        }

        [Route(URLRouting.Program.DeleteProgramDetails)]
        public IActionResult DeleteProgramDetails(int Id)
        {
            _programDetailRepository.DeleteProgramInfo(Id);

            return RedirectToAction(ControllersList.ProgramDetailsController.ActionViewProgramDetails);
        }

    }
}

Source/TechTalkDemo.ASPNETCore2.2/TechTalkDemo.ASPNETCore2.2/Areas/ProgramDetails/Views/ProgramDetail/AddProgramDetails.cshtml
@model ProgramDetail;


<style>
    .error {
        color: red;
        margin-left: 5px;
    }
</style>

<div class="row">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"> Add Program Details </h4>

                <form method="post" asp-action="SaveProgram" id="frmProgramDetails">
                    <div class="form-group">
                        <label for="exampleInputUsername1">Start Year</label>
                        <input type="text" asp-for="StartYear" name="StartYear" id="txtStartYear" class="form-control" maxlength="20" placeholder="Enter Start Year" required />

                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Program Code</label>
                        <input type="text" asp-for="ProgramCode" name="ProgramCode" id="txtProgramCode" class="form-control" maxlength="20" placeholder="Enter Program Code" required />

                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Program Name</label>
                        <input type="text" asp-for="ProgramName" name="ProgramName" id="txtProgramName" class="form-control" maxlength="20" placeholder="Enter Program Name" required />

                    </div>

                    <div class="form-group">
                        <label for="exampleInputPassword1">Duration</label>
                        <input type="text" asp-for="Duration" name="Duration" id="txtDuratione" class="form-control" maxlength="20" placeholder="Enter Duration" required />

                    </div>

                    <div class="form-group">
                        <label for="exampleInputPassword1">Program Type</label>
                        <input type="text" asp-for="ProgramType" name="ProgramType" id="txtProgramType" class="form-control" maxlength="20" placeholder="Enter ProgramType" required />

                    </div>


                    <div class="form-group">
                        <label for="exampleInputPassword1">Program Desc</label>
                        <input type="text" asp-for="ProgramDesc" name="ProgramDesc" id="txtProgramDesc" class="form-control" maxlength="20" placeholder="Enter Program esc" required />

                    </div>



                    <button type="submit" class="btn btn-primary mr-2">Save</button>
                    <a href="~/program-details" class="btn btn-light" >Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>







<script src="~/Theme/js/jquery-3.6.0.js"></script>
<script src="~/Theme/js/jquery.validate.js"></script>
<script src="~/Theme/js/additional-methods.js"></script>

<script>

            $(document).ready(function () {
                $("#frmProgramDetails").validate({
                    rules: {
                        "StartYear": {
                            required: true
                        },
                        "ProgramCode": {
                            required: true
                        },
                        "ProgramName": {
                            required: true
                        } 
                    },
                    messages: {
                        "StartYear": {
                            required: "Please, Enter a Start Year"
                        },
                        "ProgramCode": {
                            required: "Please, Enter a Program Code"

                        },
                        "ProgramName": {
                            required: "Please, Enter a Program Name"
                        } 
                        
                    },
                    submitHandler: function (form) { // for demo
                        //alert('valid form submitted'); // for demo
                        return false; // for demo
                    }
                });

            });
</script>

Source/TechTalkDemo.ASPNETCore2.2/TechTalkDemo.ASPNETCore2.2/Areas/ProgramDetails/Views/ProgramDetail/ViewProgramDetails.cshtml
@model DataTable;

<div class="card">
    <div class="card-body">
        <h4 class="card-title"> Program Details </h4>
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Action</th>
                    <th>Start Year</th>
                    <th>Program Code</th>
                    <th>Program Name</th>
                    <th>Duration</th>
                    <th>ProgramType</th>
                    <th>ProgramDesc</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Rows != null && Model.Rows.Count > 0)
                {
                    int i = 1;
                    @foreach (DataRow Item in Model.Rows)
                    {
                <tr>
                    <td>
                        <a   asp-route-Id="@Item[DBFields.ProgramDetails.ProgramId]" asp-controller="ProgramDetail" asp-action="EditProgramDetails">
                            <i class="icon-pencil"></i>
                        </a>
                        <a  asp-route-Id="@Item[DBFields.ProgramDetails.ProgramId]" asp-controller="ProgramDetail" asp-action="DeleteProgramDetails">
                            <i class="icon-trash"></i>
                        </a>
                    </td>
                    <td> @Item[DBFields.ProgramDetails.StartYear]</td>
                    <td> @Item[DBFields.ProgramDetails.ProgramCode]</td>
                    <td> @Item[DBFields.ProgramDetails.ProgramName]</td>
                    <td> @Item[DBFields.ProgramDetails.Duration]</td>
                    <td> @Item[DBFields.ProgramDetails.ProgramType]</td>
                    <td> @Item[DBFields.ProgramDetails.ProgramDesc]</td>
                </tr>
                        i++;
                    }
                }
            </tbody>
        </table>
    </div>
</div>