Source/TechTalkDemo.ASPNETCore2.2/TechTalkDemo.ASPNETCore2.2/Areas/Student/Controllers/StudentInfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using TechTalkDemo.ASPNETCore2._2.Areas.Student.Data;
using TechTalkDemo.ASPNETCore2._2.Areas.Student.Models;
using TechTalkDemo.Common;
/// <summary>
/// 
/// </summary>
namespace TechTalkDemo.ASPNETCore2._2.Areas.Student.Controllers
{
    [Area(TechTalkDemo.Common.AreaName.Student)]
   
    public class StudentInfoController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IStudentRepository _iStudentRepository;
        StudentCommanModels studentcommanmodels = new StudentCommanModels();

        public StudentInfoController(IConfiguration configuration, IStudentRepository iStudentRepository)
        {
            _configuration = configuration;
            _iStudentRepository = iStudentRepository;
        }

       
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [Route(URLRouting.StudentInfo.AddStudentDetails)]
        public IActionResult AddStudent()
        {
            studentcommanmodels.ListDepartment = _iStudentRepository.CreateCustomersTable();
            return View(studentcommanmodels);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [Route(URLRouting.StudentInfo.StudentDetails)]
        public ActionResult ViewStudentDetails()
        {
            return View(_iStudentRepository.GetStudentDetails());
        }
        public IActionResult SaveDetails(StudentModel objModel)
        {
            _iStudentRepository.SaveStudentInfo(objModel);
            return RedirectToAction(ControllersList.StudentInfoController.ViewStudentDetails );
        }
        [Route(URLRouting.StudentInfo.EditStudentDetails)]
        public IActionResult EditStudentDetails(int StudentId)
        {

            DataTable dataTable = _iStudentRepository.GetStudentInfoById(StudentId);
            StudentModel student = new StudentModel();
            student.StudentId = Convert.ToInt32(dataTable.Rows[0][DBFields.StudentInfo.StudentId]);
            student.FirstName = dataTable.Rows[0][DBFields.StudentInfo.FirstName].ToString();
            student.LastName = dataTable.Rows[0][DBFields.StudentInfo.LastName].ToString();
            student.Department = dataTable.Rows[0][DBFields.StudentInfo.Department].ToString();
            student.MidleName = dataTable.Rows[0][DBFields.StudentInfo.MidleName].ToString();
            studentcommanmodels.studentDetails = student;
            studentcommanmodels.ListDepartment = _iStudentRepository.CreateCustomersTable(); ;
            return View(ControllersList.StudentInfoController.ViewAddStudent, studentcommanmodels);
        }
        [Route(URLRouting.StudentInfo.DeleteStudentDetails)]
        public IActionResult DeleteStudentDetails(int StudentId)
        {
            _iStudentRepository.DeleteStudentInfo(StudentId);
            return RedirectToAction(ControllersList.StudentInfoController.ViewStudentDetails);
        }
    }
}

Source/TechTalkDemo.ASPNETCore2.2/TechTalkDemo.ASPNETCore2.2/Areas/Student/Views/StudentInfo/AddStudent.cshtml
@model TechTalkDemo.ASPNETCore2._2.Areas.Student.Models.StudentCommanModels;


<style>
    .error {
        color: red;
        margin-left: 5px;
    }
</style>

<div class="row">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"> Add Student Information </h4>

                <form method="post" asp-action="SaveDetails" id="frmStudentDetails">
                    <div class="form-group">
                        <label for="exampleInputUsername1">First Name</label>
                        <input type="text" asp-for="studentDetails.FirstName" name="FirstName" id="txtFirstName" class="form-control" maxlength="20" placeholder="Enter First Name" required/>

                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Midle Name</label>
                        <input type="text" asp-for="studentDetails.MidleName" name="MidleName" id="txtMidleName" class="form-control" maxlength="20" placeholder="Enter Middle Name" required/>

                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Last Name</label>
                        <input type="text" asp-for="studentDetails.LastName" name="LastName" id="txtLastName" class="form-control" maxlength="20" placeholder="Enter Last Name" required/>

                    </div>
                    <div class="form-group">
                        <label for="exampleInputConfirmPassword1">Department</label>
                        <select asp-for="studentDetails.Department" asp-items="@(new SelectList(Model.ListDepartment,"DepartmentID","DepartmentName"))" name="Department" class="form-control" id="ddlDepartment" required>
                            <option value="">Select</option>
                        </select>
                    </div>

                    <button type="submit" class="btn btn-primary mr-2">Save</button>
                    <button class="btn btn-light">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>





 

        <script src="~/Theme/js/jquery-3.6.0.js"></script>
        <script src="~/Theme/js/jquery.validate.js"></script>
        <script src="~/Theme/js/additional-methods.js"></script> 

        <script>

            $(document).ready(function () {
                $("#frmStudentDetails").validate({
                    rules: {
                        "FirstName": {
                            required: true
                        },
                        "MidleName": {
                            required: true
                        },
                        "LastName": {
                            required: true
                        },
                        "Department": {
                            required: true
                        }
                    },
                    messages: {
                        "FirstName": {
                            required: "Please, Enter a First Name"
                        },
                        "MidleName": {
                            required: "Please, Enter a Middle Name"

                        },
                        "LastName": {
                            required: "Please, Enter a Last Name"
                        },
                        "Department": {
                            required: "Please, Select a Department"
                        }
                    },
                    submitHandler: function (form) { // for demo
                        //alert('valid form submitted'); // for demo
                        return false; // for demo
                    }
                });

            });
        </script>

Source/TechTalkDemo.ASPNETCore2.2/TechTalkDemo.ASPNETCore2.2/Areas/Student/Views/StudentInfo/ViewStudentDetails.cshtml
@model DataTable;

<div class="card">
    <div class="card-body">
        <h4 class="card-title"> Student Information </h4>
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Action</th>
                    <th>First Name</th>
                    <th>Middle Name</th>
                    <th>Last Name</th>
                    <th>Department</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Rows != null && Model.Rows.Count > 0)
                {
                    int i = 1;
                    @foreach (DataRow Item in Model.Rows)
                    {
                        <tr>
                            <td>
                                <a asp-area="Student" asp-route-StudentID="@Item[DBFields.StudentInfo.StudentId]" asp-controller="StudentInfo" asp-action="EditStudentDetails">
                                    <i class="icon-pencil"></i>
                                </a>
                                <a asp-area="Student" asp-route-StudentID="@Item[DBFields.StudentInfo.StudentId]" asp-controller="StudentInfo" asp-action="DeleteStudentDetails">
                                    <i class="icon-trash"></i>
                                </a>
                            </td>
                            <td> @Item[DBFields.StudentInfo.FirstName]</td>
                            <td> @Item[DBFields.StudentInfo.MidleName]</td>
                            <td> @Item[DBFields.StudentInfo.LastName]</td>
                            <td> @Item[DBFields.StudentInfo.Department]</td>
                        </tr>
                        i++;
                    }
                }
            </tbody>
        </table>
    </div>
</div>